[35mDEBUG   [0m log_name:base.py:94 点击元素:用户中心
[35mDEBUG   [0m log_name:base.py:94 点击元素:收货地址
[35mDEBUG   [0m log_name:base.py:94 点击元素:修改地址
[35mDEBUG   [0m log_name:base.py:164 收件人：张三
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148814343A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ed1a839a38fdf8de389d415bb62607b3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148FF649070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ed1a839a38fdf8de389d415bb62607b3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148FF66F9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ed1a839a38fdf8de389d415bb62607b3